if(EXISTS "/Users/henriklagergren/Documents/software_evolution_project/group-5-libSMCE/test/SMCE_Tests_tests-b12d07c.cmake")
  include("/Users/henriklagergren/Documents/software_evolution_project/group-5-libSMCE/test/SMCE_Tests_tests-b12d07c.cmake")
else()
  add_test(SMCE_Tests_NOT_BUILT-b12d07c SMCE_Tests_NOT_BUILT-b12d07c)
endif()
